# Generated by Django 3.0.5 on 2020-05-01 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_component_added', to=settings.AUTH_USER_MODEL)),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_component_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HighLevelReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('derived_req', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('req_statement', models.TextField(verbose_name='Requirement Statement')),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_highlevelreq_added', to=settings.AUTH_USER_MODEL)),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_highlevelreq_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'High-level Requirement',
                'verbose_name_plural': 'High-level Requirements',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('name_plural', models.CharField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('removed', models.BooleanField(default=False)),
                ('d_type', models.IntegerField(choices=[(0, 'None'), (1, 'Boolean'), (2, 'Enumeration'), (3, 'Float'), (4, 'Integer'), (5, 'String')], default=0, verbose_name='Data Type')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('t_type', models.IntegerField(choices=[(0, 'Constant'), (1, 'Definition'), (2, 'Input'), (3, 'Output'), (4, 'Variable')], default=1, verbose_name='Term Type')),
                ('boolean_false_cond', models.CharField(blank=True, max_length=140, null=True)),
                ('boolean_true_cond', models.CharField(blank=True, max_length=140, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_value', models.CharField(blank=True, max_length=140, null=True)),
                ('min_value', models.CharField(blank=True, max_length=140, null=True)),
                ('value', models.CharField(blank=True, max_length=140, null=True)),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_term_added', to=settings.AUTH_USER_MODEL)),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_term_modified', to=settings.AUTH_USER_MODEL)),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requirements.Unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SysReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('req_statement', models.TextField(verbose_name='Requirement Statement')),
                ('removed', models.BooleanField(default=False)),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_sysreq_added', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.Component')),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_sysreq_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Requirement',
                'verbose_name_plural': 'System Requirements',
            },
        ),
        migrations.CreateModel(
            name='LowLevelReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('derived_req', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('req_statement', models.TextField(verbose_name='Requirement Statement')),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_lowlevelreq_added', to=settings.AUTH_USER_MODEL)),
                ('high_level_req', models.ManyToManyField(to='requirements.HighLevelReq', verbose_name='High-level Requirement')),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_lowlevelreq_modified', to=settings.AUTH_USER_MODEL)),
                ('term', models.ManyToManyField(to='requirements.Term', verbose_name='Terms')),
            ],
            options={
                'verbose_name': 'Low-level Requirement',
                'verbose_name_plural': 'Low-level Requirements',
            },
        ),
        migrations.AddField(
            model_name='highlevelreq',
            name='sys_req',
            field=models.ManyToManyField(to='requirements.SysReq', verbose_name='System Requirement'),
        ),
        migrations.AddField(
            model_name='highlevelreq',
            name='term',
            field=models.ManyToManyField(to='requirements.Term', verbose_name='Terms'),
        ),
    ]
