# Generated by Django 3.0.5 on 2020-05-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
