# Generated by Django 3.0.5 on 2020-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_unit_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='removed',
        ),
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
